/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddAlbumModal: typeof import('./components/modals/AddAlbumModal.vue')['default']
    AppSidebar: typeof import('./components/AppSidebar.vue')['default']
    ChangeAvatarModal: typeof import('./components/modals/ChangeAvatarModal.vue')['default']
    ConfirmRemoveModal: typeof import('./components/modals/ConfirmRemoveModal.vue')['default']
    Grid4Icon: typeof import('./components/icons/Grid4Icon.vue')['default']
    Grid5Icon: typeof import('./components/icons/Grid5Icon.vue')['default']
    GridSize: typeof import('./components/shared/GridSize.vue')['default']
    Modal: typeof import('./components/shared/Modal.vue')['default']
    NavList: typeof import('./components/shared/NavList.vue')['default']
    NotFound: typeof import('./components/NotFound.vue')['default']
    PhotoManager: typeof import('./components/PhotoManager.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchFiles: typeof import('./components/shared/SearchFiles.vue')['default']
    TheCard: typeof import('./components/shared/TheCard.vue')['default']
    TheCardImage: typeof import('./components/shared/TheCardImage.vue')['default']
    TheModal: typeof import('./components/shared/TheModal.vue')['default']
  }
}
