/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/photos/[id]': RouteRecordInfo<'/photos/[id]', '/photos/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/photos/albums/[id]': RouteRecordInfo<'/photos/albums/[id]', '/photos/albums/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/photos/edit/[id]': RouteRecordInfo<'/photos/edit/[id]', '/photos/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/photos/upload': RouteRecordInfo<'/photos/upload', '/photos/upload', Record<never, never>, Record<never, never>>,
  }
}
